[global]
# Streamlit configuration for Hair Fall Prediction System

# Development settings
developmentMode = false
showErrorDetails = true

[server]
# Server configuration
port = 8503
headless = false
runOnSave = true
maxUploadSize = 20

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8503

[theme]
# Theme configuration
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

[logger]
# Logging configuration
level = "info"

[client]
# Client configuration
showErrorDetails = true
toolbarMode = "viewer"